//import { ref, computed } from 'vue'
import { defineStore } from 'pinia'

//import products from '@/data/products.json'

export const useProductStore = defineStore('productStore', {
  state: () => ({
    products: [
      {
        id: 'iPhone12',
        name: 'Apple iPhone 12',
        vendor: 'Apple',
        year: 2020,
        diagonal: 6.1,
        country: 'Китай',
        memory: 128,
        freq: 60,
        nfc: false,
        esim: true,
        wcharg: true,
        price: 81990,
        iw: 60,
        ih: 120,
        itw: 27,
        ith: 50,
      },
      {
        id: 'XiaomiMi11Lite',
        name: 'Xiaomi Mi 11 Lite',
        vendor: 'Xiaomi',
        year: 2021,
        diagonal: 6.55,
        country: 'Китай',
        memory: 128,
        freq: 90,
        nfc: true,
        esim: true,
        wcharg: false,
        price: 27490,
        iw: 59,
        ih: 120,
        itw: 27,
        ith: 50,
      },
      {
        id: 'SamsungGalaxyA72',
        name: 'Samsung Galaxy A72',
        vendor: 'Samsung',
        year: 2021,
        diagonal: 6.7,
        country: 'Вьетнам',
        memory: 128,
        freq: 90,
        nfc: true,
        esim: false,
        wcharg: true,
        price: 32890,
        iw: 59,
        ih: 120,
        itw: 26,
        ith: 50,
      },
      {
        id: 'iPhoneXr',
        name: 'Apple iPhone Xr',
        vendor: 'Apple',
        year: 2018,
        diagonal: 6.1,
        country: 'Китай',
        memory: 64,
        freq: 60,
        nfc: true,
        esim: false,
        wcharg: true,
        price: 25000,
        iw: 62,
        ih: 120,
        itw: 26,
        ith: 50,
      },
      {
        id: 'Realme8Pro',
        name: 'Realme 8Pro',
        vendor: 'Realme',
        year: 2021,
        diagonal: 6.4,
        country: 'Китай',
        memory: 128,
        freq: 60,
        nfc: true,
        esim: false,
        wcharg: false,
        price: 24990,
        iw: 57,
        ih: 120,
        itw: 26,
        ith: 50,
      },
      {
        id: 'SamsungGalaxyS21',
        name: 'Samsung Galaxy S21',
        vendor: 'Samsung',
        year: 2021,
        diagonal: 6.2,
        country: 'Южная Корея',
        memory: 256,
        freq: 120,
        nfc: true,
        esim: true,
        wcharg: true,
        price: 28075,
        iw: 58,
        ih: 120,
        itw: 24,
        ith: 50,
      },
      {
        id: 'HONORX9cSmart',
        name: 'HONOR X9c Smart',
        vendor: 'HONOR',
        year: 2024,
        diagonal: 6.8,
        country: 'Китай',
        memory: 256,
        freq: 120,
        nfc: true,
        esim: true,
        wcharg: false,
        price: 23499,
        iw: 57,
        ih: 120,
        itw: 24,
        ith: 50,
      },
      {
        id: 'HUAWEI_Pura80Pro',
        name: 'HUAWEI Pura80 Pro',
        vendor: 'HUAWEI',
        year: 2025,
        diagonal: 6.8,
        country: 'Китай',
        memory: 512,
        freq: 120,
        nfc: true,
        esim: true,
        wcharg: true,
        price: 89999,
        iw: 57,
        ih: 120,
        itw: 24,
        ith: 50,
      },
    ],
  }),
})
